import { describe, it, expect, vi, beforeAll, afterEach } from "vitest";
import { mkdtemp, rm, stat, readFile, writeFile, chmod, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import {
  AUTH_COOKIE_NAMES,
  CookieService,
  COOKIE_JAR_FILE,
  PROBE_VIDEO_ID,
  countCookieLines,
  defaultJarPath,
  extractedCookieCount,
  hasAuthCookie,
  type CookieServiceDeps,
} from "./index.js";
import type { YtDlpRun } from "../youtube/ytdlp.js";
import { YtError, YtErrorKind } from "../youtube/errors.js";
import { createLogger, setRootLogger } from "../util/logger.js";
import type { TrackMeta } from "../types/index.js";

/**
 * The cookie console's contract, and above all its ONE security invariant: a cookie VALUE never
 * leaves the module. Every test that pastes anything pastes SECRET so the assertion can be the
 * blunt one — "this string appears NOWHERE in what the caller got back".
 *
 * A recognizable, unmistakable value: if it ever shows up in a reason, a health blob or a log
 * line, the leak is unambiguous rather than a judgement call about what counts as sensitive.
 */
const SECRET = "s3cr3t-SID-value-do-not-echo-9f2a1c";

/** The other half of a real jar: the HttpOnly auth cookie a browser export marks with a prefix. */
const SECRET2 = "s3cr3t-HSID-value-do-not-echo-4b7e0d";

const meta: TrackMeta = {
  videoId: PROBE_VIDEO_ID,
  title: "Me at the zoo",
  channel: "jawed",
  durationSec: 19,
  isLive: false,
  thumbnailUrl: null,
};

beforeAll(() => {
  // writeJar and the import's promote step log their failures through the root logger; the failure
  // paths below are deliberate, so keep the suite's output clean (and prove nothing crashes when
  // it logs).
  setRootLogger(createLogger("silent"));
});

const dirs: string[] = [];
afterEach(async () => {
  await Promise.all(dirs.splice(0).map((d) => rm(d, { recursive: true, force: true })));
});

async function tmp(prefix = "ytbot-cookies-"): Promise<string> {
  const dir = await mkdtemp(join(tmpdir(), prefix));
  dirs.push(dir);
  return dir;
}

function okRun(over: Partial<YtDlpRun> = {}): YtDlpRun {
  return { stdout: "", stderr: "", code: 0, ...over };
}

async function make(over: Partial<CookieServiceDeps> = {}) {
  const cacheDir = await tmp();
  const jarPath = defaultJarPath(cacheDir);
  const resolve = vi.fn(async (_id: string): Promise<TrackMeta> => meta);
  const applyCookies = vi.fn<(path: string | null) => void>();
  const run = vi.fn(async (_args: string[], _timeoutMs: number): Promise<YtDlpRun> => okRun());
  const svc = new CookieService({
    cacheDir,
    jarPath,
    youtube: { resolve },
    browserProfile: null,
    applyCookies,
    run,
    now: () => 1_700_000_000_000,
    ...over,
  });
  return { svc, cacheDir, jarPath, resolve, applyCookies, run };
}

/** File permission bits, as an octal string — the jar must be 0600 and nothing looser. */
async function mode(path: string): Promise<string> {
  return ((await stat(path)).mode & 0o777).toString(8);
}

// A genuine cookies.txt export: the header line, a plain cookie, and the `#HttpOnly_` form that
// carries the auth cookies which actually matter (and which a naive "#" = comment parse drops).
const NETSCAPE_EXPORT = [
  "# Netscape HTTP Cookie File",
  "# This file is generated by yt-dlp.  Do not edit.",
  "",
  `.youtube.com\tTRUE\t/\tTRUE\t2000000000\tSID\t${SECRET}`,
  `#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t2000000000\tHSID\t${SECRET2}`,
  "",
].join("\n");

// The other thing an operator will paste: one line copied out of DevTools' request headers.
const HEADER_PASTE = `Cookie: SID=${SECRET}; HSID=${SECRET2}; PREF=tz=Etc.UTC`;

/**
 * The eight cookies youtube.com hands an ANONYMOUS visitor, and therefore what
 * `--cookies-from-browser <empty profile> --cookies OUT` actually leaves in OUT: yt-dlp writes the
 * jar AFTER the HTTP request, so the response's own Set-Cookies land in it even when the profile
 * held nothing at all. Reproduced from a real run against a zero-cookie profile — this is the exact
 * input that used to pass every check and overwrite a working session with an anonymous one.
 */
const ANONYMOUS_JAR = [
  "# Netscape HTTP Cookie File",
  "# This file is generated by yt-dlp.  Do not edit.",
  "",
  ".youtube.com\tTRUE\t/\tFALSE\t2000000000\tPREF\ttz=Etc.UTC",
  ".youtube.com\tTRUE\t/\tTRUE\t2000000000\tSOCS\tCAI",
  "#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t2000000000\t__Secure-YNID\tanon-ynid",
  ".youtube.com\tTRUE\t/\tTRUE\t2000000000\tGPS\t1",
  "#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t2000000000\tYSC\tanon-ysc",
  ".youtube.com\tTRUE\t/\tTRUE\t2000000000\t__Secure-ROLLOUT_TOKEN\tanon-rollout",
  "#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t2000000000\tVISITOR_INFO1_LIVE\tanon-visitor",
  "#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t2000000000\tVISITOR_PRIVACY_METADATA\tanon-privacy",
  "",
].join("\n");

/** What a REAL import looks like: those same eight, plus the one cookie that proves a session. */
const SIGNED_IN_JAR = [
  ANONYMOUS_JAR.trimEnd(),
  `#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t2000000000\t__Secure-1PSID\t${SECRET}`,
  "",
].join("\n");

/**
 * Why the sign-in check insists on a NON-EMPTY value. yt-dlp's `unpad_pkcs7` does no validation, so
 * a wrong-key decrypt yields a perfectly well-formed 7-field line whose value column is the empty
 * string. By NAME this jar is signed in; it authenticates nothing.
 */
const EMPTY_AUTH_JAR = [
  ANONYMOUS_JAR.trimEnd(),
  "#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t2000000000\t__Secure-1PSID\t",
  "",
].join("\n");

// Copied VERBATIM out of src/cookies/index.ts. The console UI and the README quote the same
// sentences, so a quiet reword surfaces here as a failure instead of as three files disagreeing.
const NOT_SIGNED_IN =
  "that profile is not signed in to YouTube — sign in inside the browser sidecar, wait ~30s for Chromium to flush its cookies, then Import again";
const PROFILE_EMPTY =
  "yt-dlp read that profile but found no cookies at all — check COOKIE_BROWSER_PROFILE points at the chromium user-data-dir";
const NO_COOKIE_DB =
  "no chromium cookie database under that profile — is the sidecar up, and does its PUID match the bot's uid 10001?";
const NO_AUTH_PASTE =
  "saved, but this jar carries no YouTube sign-in cookies (SID / __Secure-1PSID) — it will not get you past a bot check";
const UNDECRYPTABLE =
  "some cookies in that profile could not be decrypted and were dropped — the sidecar must run with --password-store=basic";

/**
 * A chromium profile directory as yt-dlp expects to find one: a cookie DB where the network
 * service actually puts it. The profile probe now refuses a directory with no DB under it, so
 * every import test needs a real one — a bare tmp dir is the "COOKIE_BROWSER_PROFILE is aimed one
 * level off the user-data-dir" case, not a healthy sidecar.
 */
async function profileWithDb(rel = "Default/Network/Cookies"): Promise<string> {
  const dir = await tmp("jukebox-profile-");
  const db = join(dir, rel);
  await mkdir(dirname(db), { recursive: true });
  await writeFile(db, "SQLite format 3\u0000");
  return dir;
}

/**
 * A yt-dlp stand-in that writes `jar` to whatever `--cookies` names — i.e. to the STAGED file,
 * exactly as the real thing does — and remembers the path so a test can prove it was cleaned up.
 */
function runWriting(jar: string, over: Partial<YtDlpRun> = {}) {
  const seen: { staged: string } = { staged: "" };
  const run = vi.fn(async (args: string[]): Promise<YtDlpRun> => {
    seen.staged = args[args.indexOf("--cookies") + 1] ?? "";
    await writeFile(seen.staged, jar);
    return okRun(over);
  });
  return { run, seen };
}

describe("countCookieLines", () => {
  it("counts 7-field lines including the #HttpOnly_ ones, and no comments", () => {
    expect(countCookieLines(NETSCAPE_EXPORT)).toBe(2);
    expect(countCookieLines("# Netscape HTTP Cookie File\n\n")).toBe(0);
    expect(countCookieLines("")).toBe(0);
  });
});

describe("defaultJarPath", () => {
  it("is <cacheDir>/yt-cookies.txt — the same file materializeCookies writes", () => {
    expect(defaultJarPath("/data/cache")).toBe(join("/data/cache", COOKIE_JAR_FILE));
    expect(COOKIE_JAR_FILE).toBe("yt-cookies.txt");
  });
});

describe("CookieService.saveFromText", () => {
  it("accepts a Netscape cookies.txt export: writes the jar 0600 and hot-applies it", async () => {
    const { svc, jarPath, applyCookies, resolve } = await make();

    const res = await svc.saveFromText(NETSCAPE_EXPORT);

    expect(res).toEqual({ ok: true, reason: null });
    // The export is kept as-is (both cookie lines survive, HttpOnly prefix included).
    const jar = await readFile(jarPath, "utf8");
    expect(countCookieLines(jar)).toBe(2);
    expect(jar).toContain("#HttpOnly_.youtube.com");
    // A logged-in Google session on a shared volume: owner-only, always.
    expect(await mode(jarPath)).toBe("600");
    // Hot-applied — the NEXT yt-dlp run uses it, with no restart.
    expect(applyCookies).toHaveBeenCalledWith(jarPath);
    // …and proven with a real extraction rather than reported as "saved" on faith.
    expect(resolve).toHaveBeenCalledWith(PROBE_VIDEO_ID);
  });

  it('accepts a one-line "Cookie: a=b; c=d" header: converts, writes 0600 and hot-applies', async () => {
    const { svc, jarPath, applyCookies } = await make();

    const res = await svc.saveFromText(HEADER_PASTE);

    expect(res).toEqual({ ok: true, reason: null });
    const jar = await readFile(jarPath, "utf8");
    expect(jar.startsWith("# Netscape HTTP Cookie File")).toBe(true);
    // Three name=value pairs became three tab-separated cookie lines.
    expect(countCookieLines(jar)).toBe(3);
    expect(jar).toContain(`\tSID\t${SECRET}`);
    expect(await mode(jarPath)).toBe("600");
    expect(applyCookies).toHaveBeenCalledWith(jarPath);
  });

  it("writes 0600 even when a looser jar already exists (tmp + rename, not a truncate)", async () => {
    const { svc, cacheDir, jarPath, applyCookies } = await make();
    await mkdir(cacheDir, { recursive: true });
    await writeFile(jarPath, "# stale\n");
    await chmod(jarPath, 0o644);

    expect(await svc.saveFromText(HEADER_PASTE)).toEqual({ ok: true, reason: null });

    expect(await mode(jarPath)).toBe("600");
    expect(await readFile(jarPath, "utf8")).not.toContain("# stale");
    expect(applyCookies).toHaveBeenCalledWith(jarPath);
  });

  it("reports source/updatedAt through health() once it has written a jar", async () => {
    const { svc } = await make({ now: () => 1234 });

    expect(svc.health()).toEqual({
      configured: false,
      source: "none",
      updatedAt: null,
      lastCheck: null,
      browserProfileAvailable: false,
    });

    await svc.saveFromText(HEADER_PASTE);

    expect(svc.health()).toEqual({
      configured: true,
      source: "paste",
      updatedAt: 1234,
      lastCheck: { at: 1234, ok: true, reason: null },
      browserProfileAvailable: false,
    });
  });

  it("REJECTS junk that yields no cookies — and quotes none of it back", async () => {
    const { svc, jarPath, applyCookies, resolve } = await make();
    // No "=" anywhere, so the header parser finds no name/value pair: the "I pasted the wrong
    // thing" case. The junk carries SECRET so an echo of the input is unmissable.
    const junk = `zorblat ${SECRET} quibnar`;

    const res = await svc.saveFromText(junk);

    expect(res.ok).toBe(false);
    expect(res.reason).toBe("no cookies found in that text");
    // The reason is a literal WE wrote: not one byte of the paste, not even a length or a prefix.
    // Checked word by word, so a future "reason" that helpfully quotes the input fails here.
    for (const word of junk.split(/\s+/)) expect(res.reason).not.toContain(word);
    // A rejected paste changes nothing: no jar on disk, nothing hot-applied, no probe spent.
    await expect(stat(jarPath)).rejects.toMatchObject({ code: "ENOENT" });
    expect(applyCookies).not.toHaveBeenCalled();
    expect(resolve).not.toHaveBeenCalled();
    expect(svc.health().configured).toBe(false);
  });

  it("rejects an empty / whitespace-only box the same way", async () => {
    const { svc, applyCookies } = await make();
    for (const junk of ["", "   \n\t\n ", "# Netscape HTTP Cookie File\n"]) {
      const res = await svc.saveFromText(junk);
      expect(res).toEqual({ ok: false, reason: "no cookies found in that text" });
    }
    expect(applyCookies).not.toHaveBeenCalled();
  });

  it("returns the PROBE's verdict, so a saved-but-still-blocked jar never reads as working", async () => {
    const resolve = vi.fn(async (): Promise<TrackMeta> => {
      throw new YtError(YtErrorKind.IpBlocked, "Sign in to confirm you're not a bot");
    });
    const { svc, jarPath, applyCookies } = await make({ youtube: { resolve } });

    const res = await svc.saveFromText(HEADER_PASTE);

    expect(res).toEqual({ ok: false, reason: "sign-in / bot check" });
    // The jar WAS written and applied — the operator's paste is not thrown away because
    // YouTube is still unhappy; only the verdict is negative.
    expect(await mode(jarPath)).toBe("600");
    expect(applyCookies).toHaveBeenCalledWith(jarPath);
    expect(svc.health().lastCheck).toEqual({
      at: 1_700_000_000_000,
      ok: false,
      reason: "sign-in / bot check",
    });
  });

  it("reports an unwritable CACHE_DIR without applying anything", async () => {
    // A path whose parent is a FILE: mkdir -p and writeFile both fail, like a full disk would.
    const cacheDir = await tmp();
    const notADir = join(cacheDir, "wall");
    await writeFile(notADir, "");
    const { svc, applyCookies, resolve } = await make({
      cacheDir: join(notADir, "cache"),
      jarPath: join(notADir, "cache", COOKIE_JAR_FILE),
    });

    const res = await svc.saveFromText(HEADER_PASTE);

    expect(res.ok).toBe(false);
    expect(res.reason).toBe("could not write the cookie jar (disk full or CACHE_DIR unwritable?)");
    expect(res.reason).not.toContain(SECRET);
    expect(applyCookies).not.toHaveBeenCalled();
    expect(resolve).not.toHaveBeenCalled();
  });

  it("SAVES a consent-only paste, and warns that it carries no sign-in cookie", async () => {
    const { svc, jarPath, applyCookies } = await make();
    // Exactly what `document.cookie` yields: the auth cookies are HttpOnly, so they are simply not
    // in that string. The paste is legitimate (a consent jar clears the EU interstitial) and the
    // probe passes on an unflagged IP — but "it worked" would send the operator off believing they
    // had installed a session.
    const res = await svc.saveFromText("Cookie: PREF=tz=Etc.UTC; SOCS=CAI; YSC=abc");

    expect(res).toEqual({ ok: true, reason: null, warning: NO_AUTH_PASTE });
    // Saved and applied, not rejected — the warning rides ALONGSIDE the success.
    expect(countCookieLines(await readFile(jarPath, "utf8"))).toBe(3);
    expect(applyCookies).toHaveBeenCalledWith(jarPath);
  });

  it("attaches no warning at all when the paste really does carry a sign-in cookie", async () => {
    const { svc } = await make();
    expect((await svc.saveFromText(NETSCAPE_EXPORT)).warning).toBeUndefined();
    expect((await svc.saveFromText(HEADER_PASTE)).warning).toBeUndefined();
  });
});

describe("CookieService.test", () => {
  it("resolves the probe video and records the verdict in health()", async () => {
    const { svc, resolve } = await make({ now: () => 42 });

    expect(await svc.test()).toEqual({ ok: true, reason: null });

    expect(resolve).toHaveBeenCalledExactlyOnceWith(PROBE_VIDEO_ID);
    expect(svc.health().lastCheck).toEqual({ at: 42, ok: true, reason: null });
  });

  it("maps yt-dlp failure KINDS to fixed operator-facing reasons", async () => {
    const cases: ReadonlyArray<[unknown, string]> = [
      [new YtError(YtErrorKind.IpBlocked, "x"), "sign-in / bot check"],
      [new YtError(YtErrorKind.RateLimited, "x"), "rate-limited by YouTube"],
      [new YtError(YtErrorKind.Timeout, "x"), "yt-dlp timed out"],
      [new YtError(YtErrorKind.PoTokenSabr, "x"), "extraction blocked (po_token / sabr)"],
      [new YtError(YtErrorKind.Unavailable, "x"), "unavailable"],
      [
        Object.assign(new Error("spawn yt-dlp ENOENT"), { code: "ENOENT" }),
        "yt-dlp is not installed",
      ],
      [new Error("something else"), "extraction failed"],
    ];
    for (const [err, reason] of cases) {
      const { svc } = await make({
        youtube: {
          resolve: vi.fn(async (): Promise<TrackMeta> => {
            throw err;
          }),
        },
      });
      expect(await svc.test()).toEqual({ ok: false, reason });
    }
  });
});

describe("CookieService.importFromBrowser", () => {
  it("with NO profile configured: a clear ok:false, and nothing is spawned", async () => {
    const { svc, run, applyCookies, resolve } = await make({ browserProfile: null });

    const res = await svc.importFromBrowser();

    expect(res).toEqual({
      ok: false,
      reason: "no browser profile configured (set COOKIE_BROWSER_PROFILE)",
    });
    // The whole point: no yt-dlp, no probe, no state change when the sidecar isn't deployed.
    expect(run).not.toHaveBeenCalled();
    expect(applyCookies).not.toHaveBeenCalled();
    expect(resolve).not.toHaveBeenCalled();
    expect(svc.health().browserProfileAvailable).toBe(false);
  });

  it("with a profile configured: invokes yt-dlp with --cookies-from-browser AND --cookies", async () => {
    const profile = await profileWithDb();
    const cacheDir = await tmp();
    const jarPath = defaultJarPath(cacheDir);
    // yt-dlp given both flags SAVES the resulting jar to whatever --cookies names. We import into
    // a STAGED file, never the live jar: yt-dlp LOADS --cookies too and saves the MERGE, so writing
    // straight into the live jar means the stale cookies we are replacing survive the import.
    let sawCookiesArg: string | undefined;
    const run = vi.fn(async (args: string[]): Promise<YtDlpRun> => {
      sawCookiesArg = args[args.indexOf("--cookies") + 1];
      await writeFile(sawCookiesArg!, NETSCAPE_EXPORT, { mode: 0o644 });
      return okRun();
    });
    const { svc, applyCookies, resolve } = await make({
      cacheDir,
      jarPath,
      browserProfile: profile,
      run,
      ytdlpTimeoutMs: 12_345,
    });

    const res = await svc.importFromBrowser();

    expect(res).toEqual({ ok: true, reason: null });
    expect(run).toHaveBeenCalledOnce();
    const [args, timeoutMs] = run.mock.calls[0] as unknown as [string[], number];
    // The pairing IS the feature: read the live profile, write the merged jar to OUR file.
    expect(args).toContain("--cookies-from-browser");
    expect(args[args.indexOf("--cookies-from-browser") + 1]).toBe(`chromium:${profile}`);
    expect(args).toContain("--cookies");
    // Staged NEXT TO the jar, not the jar itself — so a refresh genuinely replaces stale cookies
    // and a failed import cannot damage a jar that currently works.
    expect(sawCookiesArg).not.toBe(jarPath);
    expect(sawCookiesArg!.startsWith(`${jarPath}.import.`)).toBe(true);
    // …and the staged jar is PROMOTED over the live one on success, with the staging file cleaned up.
    expect(await readFile(jarPath, "utf8")).toBe(NETSCAPE_EXPORT);
    expect(existsSync(sawCookiesArg!)).toBe(false);
    // Metadata only — never pull the audio just to harvest cookies.
    expect(args).toContain("--skip-download");
    expect(args).toContain("--simulate");
    // …but NOT --no-warnings, which every other yt-dlp call in the bot passes. A cookie yt-dlp
    // cannot decrypt is reported as a WARNING and then dropped silently, and that warning is the
    // only way the success path can tell the operator their sidecar grew a keyring.
    expect(args).not.toContain("--no-warnings");
    expect(args[args.length - 1]).toBe(`https://www.youtube.com/watch?v=${PROBE_VIDEO_ID}`);
    expect(timeoutMs).toBe(12_345);
    // Imported jars get the same treatment as pasted ones: 0600, hot-applied, then proven.
    expect(await mode(jarPath)).toBe("600");
    expect(applyCookies).toHaveBeenCalledWith(jarPath);
    expect(resolve).toHaveBeenCalledWith(PROBE_VIDEO_ID);
    expect(svc.health()).toMatchObject({
      configured: true,
      source: "browser",
      browserProfileAvailable: true,
    });
  });

  it("refuses a profile path yt-dlp would parse as a keyring/container, without spawning", async () => {
    for (const profile of ["/browser/profile:1", "/browser+gnomekeyring"]) {
      const { svc, run } = await make({ browserProfile: profile });
      expect(await svc.importFromBrowser()).toEqual({
        ok: false,
        reason: "the browser profile path may not contain ':' or '+'",
      });
      expect(run).not.toHaveBeenCalled();
    }
  });

  it("says the sidecar is down when the profile dir is absent, without spawning", async () => {
    const { svc, run } = await make({ browserProfile: join(await tmp(), "never-mounted") });

    expect(await svc.importFromBrowser()).toEqual({
      ok: false,
      reason: "the browser profile is not readable (is the sidecar up?)",
    });
    expect(run).not.toHaveBeenCalled();
    expect(svc.health().browserProfileAvailable).toBe(false);
  });

  it("reports an EMPTY profile when yt-dlp exits clean with no cookie lines staged", async () => {
    const profile = await profileWithDb();
    const cacheDir = await tmp();
    const jarPath = defaultJarPath(cacheDir);
    // A header and nothing under it. yt-dlp ran and had nothing to write, which is a plumbing
    // problem (the wrong directory) and a different fix from "go and sign in".
    const { run } = runWriting("# Netscape HTTP Cookie File\n");
    const { svc, applyCookies } = await make({ cacheDir, jarPath, browserProfile: profile, run });

    expect(await svc.importFromBrowser()).toEqual({ ok: false, reason: PROFILE_EMPTY });
    expect(applyCookies).not.toHaveBeenCalled();
  });

  it("reports an EMPTY profile when yt-dlp exits clean without staging a file at all", async () => {
    const profile = await profileWithDb();
    const { svc, applyCookies } = await make({
      browserProfile: profile,
      run: vi.fn(async (): Promise<YtDlpRun> => okRun()),
    });

    expect(await svc.importFromBrowser()).toEqual({ ok: false, reason: PROFILE_EMPTY });
    expect(applyCookies).not.toHaveBeenCalled();
  });

  it("translates a non-zero exit into a fixed reason and never echoes stderr", async () => {
    const profile = await profileWithDb();
    const cases: ReadonlyArray<[string, string]> = [
      [
        `could not find chromium cookies database in ${SECRET}`,
        "no chromium profile at that path — check the sidecar's volume mount",
      ],
      [
        `unable to open database file ${SECRET}`,
        "could not read the browser's cookie database (wrong profile dir, or it is locked)",
      ],
      [
        `Failed to decrypt with DPAPI keyring ${SECRET}`,
        "could not decrypt the browser cookies (the sidecar's keyring is unavailable)",
      ],
      // Nothing recognized: fall back to the shared classifier's ENUM KIND, never its message.
      [`boom ${SECRET}`, "unknown"],
    ];
    for (const [stderr, reason] of cases) {
      const { svc, applyCookies } = await make({
        browserProfile: profile,
        run: vi.fn(async (): Promise<YtDlpRun> => okRun({ stderr, code: 1 })),
      });
      const res = await svc.importFromBrowser();
      expect(res).toEqual({ ok: false, reason });
      expect(res.reason).not.toContain(SECRET);
      expect(applyCookies).not.toHaveBeenCalled();
    }
  });

  it("survives a yt-dlp that is not installed / times out", async () => {
    const profile = await profileWithDb();
    const { svc } = await make({
      browserProfile: profile,
      run: vi.fn(async (): Promise<YtDlpRun> => {
        throw new YtError(YtErrorKind.Timeout, `yt-dlp timed out reading ${SECRET}`);
      }),
    });
    const res = await svc.importFromBrowser();
    expect(res).toEqual({ ok: false, reason: "yt-dlp timed out" });
    expect(res.reason).not.toContain(SECRET);
  });
});

describe("CookieService security: a cookie value never leaves the module", () => {
  /** Every string the caller can see, from every method, concatenated for one blunt assertion. */
  async function everythingTheCallerSees(svc: CookieService): Promise<string> {
    const parts = [
      JSON.stringify(svc.health()),
      JSON.stringify(await svc.test()),
      JSON.stringify(await svc.saveFromText(NETSCAPE_EXPORT)),
      JSON.stringify(await svc.saveFromText(HEADER_PASTE)),
      JSON.stringify(await svc.saveFromText(`garbage paste holding ${SECRET}`)),
      JSON.stringify(await svc.importFromBrowser()),
      JSON.stringify(svc.health()),
    ];
    return parts.join("\n");
  }

  it("leaks nothing through a HEALTHY console", async () => {
    const { svc } = await make();
    const out = await everythingTheCallerSees(svc);
    expect(out).not.toContain(SECRET);
    expect(out).not.toContain(SECRET2);
  });

  it("leaks nothing when yt-dlp fails with our own cookies quoted in its stderr", async () => {
    // The realistic nightmare: yt-dlp echoes the cookie file it choked on, or a Set-Cookie from
    // the response, into stderr — and classifyYtdlpError puts a 500-char slice of that in
    // err.message. Nothing may forward it.
    const profile = await profileWithDb();
    const resolve = vi.fn(async (): Promise<TrackMeta> => {
      throw new YtError(YtErrorKind.Unknown, `yt-dlp failed (exit 1): cookie SID=${SECRET}`);
    });
    const { svc } = await make({
      browserProfile: profile,
      youtube: { resolve },
      run: vi.fn(async (): Promise<YtDlpRun> => okRun({ stderr: `SID=${SECRET}`, code: 1 })),
    });

    const out = await everythingTheCallerSees(svc);

    expect(out).not.toContain(SECRET);
    expect(out).not.toContain(SECRET2);
    // …and the failures really did happen (the assertion above is not vacuous).
    expect(out).toContain('"ok":false');
  });

  it("leaks nothing when the disk refuses the write", async () => {
    const cacheDir = await tmp();
    const notADir = join(cacheDir, "wall");
    await writeFile(notADir, "");
    const { svc } = await make({
      cacheDir: join(notADir, "cache"),
      jarPath: join(notADir, "cache", COOKIE_JAR_FILE),
    });

    const out = await everythingTheCallerSees(svc);

    expect(out).not.toContain(SECRET);
    expect(out).not.toContain(SECRET2);
  });

  it("keeps the jar itself off every surface: only the FILE holds the values", async () => {
    const { svc, jarPath } = await make();
    await svc.saveFromText(NETSCAPE_EXPORT);
    // The one and only place a cookie value is allowed to exist.
    expect(await readFile(jarPath, "utf8")).toContain(SECRET);
    // health() after the fact still says nothing about content — just booleans and stamps.
    const h = svc.health();
    expect(JSON.stringify(h)).not.toContain(SECRET);
    expect(Object.keys(h).sort()).toEqual([
      "browserProfileAvailable",
      "configured",
      "lastCheck",
      "source",
      "updatedAt",
    ]);
  });
});

// Both audits independently flagged this one: a jar the console wrote was silently ignored after a
// restart, because materializeCookies only returns a path when YT_COOKIES / YT_COOKIES_TEXT is set.
// The console exists precisely so an operator does NOT have to touch compose, so the jar — not the
// env var — is the artefact that must survive. src/index.ts now adopts an existing jar; this pins
// the contract the two sides agree on: defaultJarPath is where the console writes and boot looks.
describe("the console's jar is the thing that persists", () => {
  it("saveFromText writes exactly the jar path boot adopts (defaultJarPath)", async () => {
    const cacheDir = await tmp();
    const jarPath = defaultJarPath(cacheDir);
    const { svc } = await make({ cacheDir, jarPath });
    await svc.saveFromText(NETSCAPE_EXPORT);
    // The file boot will look for after a restart, with no env var set anywhere.
    expect(existsSync(defaultJarPath(cacheDir))).toBe(true);
    expect(await readFile(defaultJarPath(cacheDir), "utf8")).toContain(".youtube.com");
  });
});

// A Netscape entry is EXACTLY 7 tab-separated fields. Counting ">= 7" let a mangled paste (an extra
// tab, a copied table) pass validation, so the console reported "saved" for a jar yt-dlp then
// refuses to parse — the operator is told it worked and the bot stays silent.
describe("cookie line validation is exact", () => {
  it("rejects a paste whose lines carry MORE than 7 tab-separated fields", async () => {
    const cacheDir = await tmp();
    const { svc, applyCookies } = await make({ cacheDir, jarPath: defaultJarPath(cacheDir) });
    const mangled =
      "# Netscape HTTP Cookie File\n.youtube.com\tTRUE\t/\tTRUE\t2000000000\tSID\tv\tEXTRA\n";
    const res = await svc.saveFromText(mangled);
    expect(res.ok).toBe(false);
    expect(res.reason).toBe("no cookies found in that text");
    expect(applyCookies).not.toHaveBeenCalled(); // and nothing was applied to the live station
  });
});

// The pure half of the sign-in check. A jar is a SESSION only if it carries one of Google's auth
// cookies, for a Google domain, WITH a value — everything else is consent and preference noise.
describe("hasAuthCookie", () => {
  it("is true for any AUTH_COOKIE_NAMES entry on a google/youtube domain with a value", () => {
    expect(hasAuthCookie(SIGNED_IN_JAR)).toBe(true);
    expect(hasAuthCookie(NETSCAPE_EXPORT)).toBe(true);
    for (const name of AUTH_COOKIE_NAMES) {
      expect(hasAuthCookie(`.google.com\tTRUE\t/\tTRUE\t2000000000\t${name}\tv\n`), name).toBe(
        true,
      );
    }
    // The `#HttpOnly_` form is where the ones that matter actually live.
    expect(hasAuthCookie("#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t2000000000\tSID\tv\n")).toBe(true);
  });

  it("is false for the anonymous jar — eight cookies, not one of them a session", () => {
    // Not vacuous, and the whole defect in one line: the guard this replaces asked whether the
    // staged file had any cookie lines in it, and the answer was always yes.
    expect(countCookieLines(ANONYMOUS_JAR)).toBe(8);
    expect(hasAuthCookie(ANONYMOUS_JAR)).toBe(false);
  });

  it("is false when the value is EMPTY, however well-formed the line is", () => {
    expect(countCookieLines(EMPTY_AUTH_JAR)).toBe(9);
    expect(hasAuthCookie(EMPTY_AUTH_JAR)).toBe(false);
  });

  it("is false for an auth cookie NAME on somebody else's domain", () => {
    expect(hasAuthCookie(".evil.example\tTRUE\t/\tTRUE\t2000000000\tSID\tvalue\n")).toBe(false);
    expect(hasAuthCookie("notyoutube.com\tTRUE\t/\tTRUE\t2000000000\tSID\tvalue\n")).toBe(false);
  });

  it("tolerates CRLF, so a stray \\r never passes for a value", () => {
    expect(hasAuthCookie(".youtube.com\tTRUE\t/\tTRUE\t2000000000\tSID\t\r\n")).toBe(false);
    expect(hasAuthCookie(".youtube.com\tTRUE\t/\tTRUE\t2000000000\tSID\tv\r\n")).toBe(true);
  });
});

describe("extractedCookieCount", () => {
  it("reads yt-dlp's own count off stdout", () => {
    expect(extractedCookieCount("Extracted 0 cookies from chromium\n")).toBe(0);
    expect(
      extractedCookieCount("[youtube] jNQXAC9IVRw\nExtracted 137 cookies from chromium\n"),
    ).toBe(137);
  });

  it("is null — NOT zero — when the line is absent", () => {
    // An older yt-dlp that does not print it means "don't know", and the import has to fall
    // through to the content checks instead of rejecting a perfectly good profile.
    expect(extractedCookieCount("")).toBe(null);
    expect(extractedCookieCount("some other yt-dlp chatter\n")).toBe(null);
  });
});

// THE regression. `--cookies-from-browser P --cookies OUT` writes OUT *after* the HTTP request, so
// OUT always holds YouTube's ANONYMOUS cookies even when P is empty: countCookieLines(staged) was
// 8, the `=== 0` guard never tripped once, and an Import from a not-signed-in profile REPLACED a
// working authenticated jar with an anonymous one. probe() then passed too (PROBE_VIDEO_ID is
// public and needs no auth), so the console reported "imported and working" for the one operation
// that had just destroyed the session it was meant to install.
describe("CookieService.importFromBrowser: an anonymous jar is not a session", () => {
  it("REJECTS it, and the working jar on disk is byte-identical afterwards", async () => {
    const profile = await profileWithDb();
    const cacheDir = await tmp();
    const jarPath = defaultJarPath(cacheDir);
    // The thing the old guard destroyed: a jar that WORKS is already installed.
    await mkdir(cacheDir, { recursive: true });
    await writeFile(jarPath, NETSCAPE_EXPORT, { mode: 0o600 });
    const before = await readFile(jarPath, "utf8");
    const { run, seen } = runWriting(ANONYMOUS_JAR, {
      stdout: "Extracted 0 cookies from chromium\n",
    });
    const { svc, applyCookies, resolve } = await make({
      cacheDir,
      jarPath,
      browserProfile: profile,
      run,
    });

    expect(await svc.importFromBrowser()).toEqual({ ok: false, reason: NOT_SIGNED_IN });

    // Byte for byte: the session the operator already had survives the pointless import.
    expect(await readFile(jarPath, "utf8")).toBe(before);
    expect(await mode(jarPath)).toBe("600");
    // Nothing was hot-applied and no probe was spent — the failure is total and quiet.
    expect(applyCookies).not.toHaveBeenCalled();
    expect(resolve).not.toHaveBeenCalled();
    // The staged file is discarded, not left in CACHE_DIR holding response cookies forever.
    expect(existsSync(seen.staged)).toBe(false);
    // And the console does not claim a browser session it does not have.
    expect(svc.health().source).toBe("env");
  });

  it("REJECTS it on CONTENT alone when yt-dlp prints no count at all", async () => {
    // Older yt-dlp, no `Extracted N` line: gate (a) has nothing to say and gate (c) does the work.
    const { run } = runWriting(ANONYMOUS_JAR);
    const { svc, applyCookies, resolve } = await make({
      browserProfile: await profileWithDb(),
      run,
    });

    expect(await svc.importFromBrowser()).toEqual({ ok: false, reason: NOT_SIGNED_IN });
    expect(applyCookies).not.toHaveBeenCalled();
    expect(resolve).not.toHaveBeenCalled();
  });

  it("accepts a staged jar carrying __Secure-1PSID and promotes it over the live one", async () => {
    const profile = await profileWithDb();
    const cacheDir = await tmp();
    const jarPath = defaultJarPath(cacheDir);
    await mkdir(cacheDir, { recursive: true });
    await writeFile(jarPath, "# stale\n");
    const { run, seen } = runWriting(SIGNED_IN_JAR);
    const { svc, applyCookies, resolve } = await make({
      cacheDir,
      jarPath,
      browserProfile: profile,
      run,
    });

    expect(await svc.importFromBrowser()).toEqual({ ok: true, reason: null });

    // Promoted whole, owner-only, staging cleaned up, hot-applied, then proven.
    expect(await readFile(jarPath, "utf8")).toBe(SIGNED_IN_JAR);
    expect(await mode(jarPath)).toBe("600");
    expect(existsSync(seen.staged)).toBe(false);
    expect(applyCookies).toHaveBeenCalledWith(jarPath);
    expect(resolve).toHaveBeenCalledWith(PROBE_VIDEO_ID);
    expect(svc.health()).toMatchObject({ configured: true, source: "browser" });
  });

  it("does not count an auth cookie whose value is EMPTY as a sign-in", async () => {
    const profile = await profileWithDb();
    const cacheDir = await tmp();
    const jarPath = defaultJarPath(cacheDir);
    await mkdir(cacheDir, { recursive: true });
    await writeFile(jarPath, NETSCAPE_EXPORT, { mode: 0o600 });
    // yt-dlp says it read 41 cookies and the file is full of well-formed lines — but the one that
    // matters decrypted to nothing, which is a wrong key, not a session.
    const { run } = runWriting(EMPTY_AUTH_JAR, { stdout: "Extracted 41 cookies from chromium\n" });
    const { svc, applyCookies } = await make({ cacheDir, jarPath, browserProfile: profile, run });

    expect(await svc.importFromBrowser()).toEqual({ ok: false, reason: NOT_SIGNED_IN });
    expect(await readFile(jarPath, "utf8")).toBe(NETSCAPE_EXPORT);
    expect(applyCookies).not.toHaveBeenCalled();
  });

  it("warns about undecryptable cookies on an otherwise good import, echoing no stderr", async () => {
    const profile = await profileWithDb();
    const cacheDir = await tmp();
    const jarPath = defaultJarPath(cacheDir);
    const { run } = runWriting(SIGNED_IN_JAR, {
      stdout: "Extracted 12 cookies from chromium\n",
      stderr: `WARNING: 3 cookies could not be decrypted (SID=${SECRET})`,
    });
    const { svc, applyCookies } = await make({ cacheDir, jarPath, browserProfile: profile, run });

    const res = await svc.importFromBrowser();

    // The import SUCCEEDED — an auth cookie did survive and is installed — and the operator still
    // hears that the sidecar is dropping cookies, because that is a keyring, not a fluke.
    expect(res).toEqual({ ok: true, reason: null, warning: UNDECRYPTABLE });
    expect(JSON.stringify(res)).not.toContain(SECRET);
    expect(applyCookies).toHaveBeenCalledWith(jarPath);
  });
});

// health() runs on every page load and the Import button hangs off it, so the profile probe has to
// be cheap AND right. Three states, because the two failures have different fixes: nothing usable
// at that path (sidecar down, volume unmounted, PUID mismatch) versus a directory that reads fine
// and holds no cookie DB (COOKIE_BROWSER_PROFILE aimed at $HOME instead of the user-data-dir),
// which used to surface as a baffling yt-dlp failure halfway through an import.
describe("the sidecar profile probe has three states", () => {
  it('finds the DB at <p>/Default/Network/Cookies — "ok"', async () => {
    const { svc } = await make({ browserProfile: await profileWithDb() });
    expect(svc.health().browserProfileAvailable).toBe(true);
  });

  it('finds the DB under a second identity, <p>/Profile 1/Cookies — "ok"', async () => {
    const { svc } = await make({ browserProfile: await profileWithDb("Profile 1/Cookies") });
    expect(svc.health().browserProfileAvailable).toBe(true);
  });

  it('a readable directory with no cookie DB is "no-db", and says so without spawning', async () => {
    const { svc, run } = await make({ browserProfile: await tmp("jukebox-profile-") });

    expect(svc.health().browserProfileAvailable).toBe(false);
    expect(await svc.importFromBrowser()).toEqual({ ok: false, reason: NO_COOKIE_DB });
    expect(run).not.toHaveBeenCalled();
  });

  it('a path that is not there at all is "missing" — the sidecar-is-down reason', async () => {
    const { svc, run } = await make({ browserProfile: join(await tmp(), "never-mounted") });

    expect(svc.health().browserProfileAvailable).toBe(false);
    expect(await svc.importFromBrowser()).toEqual({
      ok: false,
      reason: "the browser profile is not readable (is the sidecar up?)",
    });
    expect(run).not.toHaveBeenCalled();
  });

  it("probes a BOUNDED set of paths — it never walks the profile looking for a DB", async () => {
    // A `Cookies` file that is NOT in one of the places chromium puts one. Walking the tree would
    // find it; the bounded probe must not, because this runs on every page load against a volume
    // a browser keeps tens of thousands of cache files in.
    const { svc } = await make({ browserProfile: await profileWithDb("Default/Cache/Cookies") });
    expect(svc.health().browserProfileAvailable).toBe(false);
  });
});
